name: Create Kind Cluster

on: push

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Kubectl describe nodes
        run: kubectl describe nodes
      - name: Download Krateo CLI for AMD64
        run: curl -L https://github.com/krateoplatformops/krateo/releases/download/v1.3.6/krateo_1.3.6_linux_amd64.deb -o krateo_1.3.6_linux_amd64.deb
      - name: Install Krateo CLI for AMD64
        run: ls -la
