name: Create OKD Cluster

on: workload_dispatch

jobs:
  example:
    name: Example OpenShift Cluster interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup OpenShift
        uses: manusa/actions-setup-openshift@v1.1.4
        with:
          oc version: '4.12.0-0.okd-2023-01-21-055900'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Interact with the cluster
        run: oc cluster status
