name: Create EKS Cluster with Kind and CAPI

on: workflow_dispatch

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Kubectl get nodes
        run: kubectl get nodes
