name: Create OKD Cluster

on: push


jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Kubectl describe nodes
        run: kubectl describe nodes
      - name: Download OC client
        run: curl https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux-4.12.0.tar.gz  -o openshift-client-linux.tar.gz
      - name: tar xvzf openshift-client-linux.tar.gz
        run: tar xvzf openshift-client-linux.tar.gz
      - name: ls -la
        run: ls -la
      - name: Move the binary oc to a directory present in your PATH
        run: sudo mv oc /usr/local/bin
      - name: Download and extract the openshift installer
        run: oc adm release extract --tools quay.io/openshift/okd:4.12.0-0.okd-2023-01-21-055900
      - name: ls -la
        run: ls -la
      - name: tar xvzf openshift-install-linux-4.12.0-0.okd-2023-01-21-055900.tar.gz
        run: tar xvzf openshift-install-linux-4.12.0-0.okd-2023-01-21-055900.tar.gz
      - name: ls -la
        run: ls -la
      - name: Move the binary openshift-install to a directory present in your PATH
        run: sudo mv openshift-install /usr/local/bin
      - name: pwd
        run: pwd
      - name: mkdir installation_directory
        run: mkdir installation_directory
      - name: Make it executable
        run: chmod +x ./installation_directory
      - name: ls -la
        run: ls -la
      - name: Initialize the cluster deployment
        run: openshift-install create cluster --dir ./installation_directory --log-level=info
